import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Script from "next/script"; // 1. Ye line add ki hai
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  // title: "Create Next App",
  title: "Bulbul - Live Streaming", // Google Title

  // Google Description
  description: "Bulbul is your go-to platform for live streaming. Watch live, Stay updated with real-time and never miss a moment of the action!.",

  // icons: {
  //   icon: '/favicon.png', // Public folder mein jo image hai uska path
  // },

  // =====================================================================
    // 👇 YE WALA HISSA ADD KAREIN (ICONS)
    icons: {
      icon: '/favicon.ico', // Ye file public folder mein honi chahiye
      shortcut: '/favicon.ico',
      apple: '/favicon.ico', // iPhone walon ke liye
    },
    
    // 👇 OPEN GRAPH (Facebook/WhatsApp par link share karne par image dikhane ke liye)
    openGraph: {
      title: 'SportsHub Live',
      description: 'Watch Live Sports Streaming',
      images: ['/logo.png'], // Agar aap chahte hain link share karne par bara logo dikhe(public folder mein logo.png hona chahiye)
    },

  // ===============================================================
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      
      {/* <head>
        Iframe load hone se pehle hi connection ready rakhne ke liye
        <link rel="preconnect" href="https://ok.ru" />
        <link rel="dns-prefetch" href="https://ok.ru" />
      </head> */}

      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {children}
        
        {/* 2. Ye Adsterra ki script yahan add ki hai */}
        <Script 
          src="https://pl28382929.effectivegatecpm.com/b1/06/0e/b1060e51e3f0ca4c6da303d42b6ea068.js" 
          strategy="afterInteractive" 
        />

        {/* yeh dosrey(bulbul) link hai social bar k */}
        <script src="https://pl28584344.effectivegatecpm.com/83/25/89/83258922d22f1be4772c2766eefae9db.js"></script>
        
      </body>
    </html>
  );
}






// =========== upper ads(adsetreaa) k script add kya hai ======================

// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body className={`${geistSans.variable} ${geistMono.variable}`}>
//         {children}
//       </body>
//     </html>
//   );
// }
